export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const CANCEL_UPDATE = "CANCEL_UPDATE";
